# Generated by Django 4.1.2 on 2022-10-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.ManyToManyField(to='main_app.language'),
        ),
    ]
